### ISSUE TITLE
kernel connecting, but not responding

### ISSUE THREAD

**Issue by durapensa** [adafruit/circuitpython_jupyter_kernel#29]
* CircuitPython Kernel version: 0.5.1 (downloaded zip from https://github.com/adafruit/circuitpython_jupyter_kernel/releases)
* Python version: 3.7.3
* Operating System: Raspbian GNU/Linux 10 (buster)

### Description

The notebook connects to the CircuitPython kernel, but hangs (solid dot to the right of of the kernel name 'CircuitPython' in the top right corner of the notebook) whenever code is executed.

### What I Did

Connected a new notebook (v6.2.0, all latest jupyter packages from PyPI) to circuitpython_kernel, using a Feather RP2040 (adafruit-circuitpython-adafruit_feather_rp2040-en_US-6.2.0-beta.3.uf2). The new notebook has `neopixel_simpletest.py` from https://circuitpython.readthedocs.io/projects/neopixel/en/latest/examples.html pasted into it.

Note that CircuitPython kernel was installed with `pip install .` as the instructions to use `python3 setup.py install` failed. `python3 -m circuitpython_kernel.install` worked with "Completed kernel installation."

The test runs fine when copying `neopixel_simpletest.py` to `code.py` on the CIRCUITPY drive.

jupyter-notebook output:
```
[I 14:42:12.916 NotebookApp] Kernel started: 5a2c643b-321c-4f8a-8ecd-97030a8b9f69, name: circuitpython                                           
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:circuitpython_kernel.kernel:circuitpython_kernel version 0.3.0.dev
[W 14:42:15.231 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20210313144140 (192.168.0.5) 6.240000ms referer=http://192.168.0.11:8888/notebooks/test.ipynb
DEBUG:circuitpython_kernel.board:/dev/ttyACM1
DEBUG:circuitpython_kernel.board:CircuitPython Board Found at: /dev/ttyACM1
DEBUG:circuitpython_kernel.board:Connected? False
DEBUG:circuitpython_kernel.board:connect: open /dev/ttyACM1
DEBUG:circuitpython_kernel.board:serial already open
DEBUG:circuitpython_kernel.board:* enter raw repl ...
```

**Comment by brentru** [comment]
@jposada202020 since you added the PR for the pico 2040 - do you have any ideas?

**Comment by jposada202020** [comment]
@brentru I will make some tests tonight with the feather RP2040, and see what could be the issue.

**Comment by jposada202020** [comment]
So I troubleshoot a little the issue. I replicate the issue using the Raspberry Pi Pico as described, and using the feather RP2040. I did not use the example provided in this issue, I was just trying to look for the root cause.  Probleme here is, that both USB port were  enabled as enhancement. People using MU and other systems  were having problems to detect the correct port. So in this case was not different. This is present in the CP beta 3 that you can download from the webpage. I downloaded the latest version from the S3 that you can find here. This built does not have two usb ports avalaible and the Notebook kernel will not get confused
https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/adafruit_feather_rp2040/en_US/

I tested this using
```python
import os
print(os.uname())
```

Produced this
```(sysname='rp2040', nodename='rp2040', release='6.2.0', version='6.2.0-beta.3-188-g05ed179e1 on 2021-03-15', machine='Adafruit Feather RP2040 with rp2040')```

The example https://github.com/adafruit/circuitpython_jupyter_kernel/blob/master/examples/CPX_Blink_Pico.ipynb works as expected using this built

Also using this was tested using a custom built to add PR regarding clock division and  was tested in
```Adafruit CircuitPython 6.2.0-beta.3-172-g550eab2dd-dirty on 2021-03-13; Adafruit Feather RP2040 with rp2040```

![image](https://user-images.githubusercontent.com/34255413/111229442-4a30f380-85bc-11eb-904a-46395fcdfdd1.png).

Could you download the lastest firmware and try again. I tested the code and it works as expected. Please use the first example as it contains the correct line for the feather

```
pixel_pin = board.NEOPIXEL
```

**Comment by durapensa** [comment]
I can report that the CircuitPython kernel is working using `adafruit-circuitpython-adafruit_feather_rp2040-en_US-20210316-921bf6d.uf2`:

```python
import os
print(os.uname())
```
```
    (sysname='rp2040', nodename='rp2040', release='6.2.0', version='6.2.0-beta.3-190-g921bf6de7 on 2021-03-16', machine='Adafruit Feather RP2040 with rp2040')
```

Many thanks! This issue can be closed.

**Comment by jposada202020** [comment]
@durapensa Thanks for re-trying, I was playing with the Jupyter Notebook during the weekend, but I guess I was lucky that I was using My built CircuitPython and not the one from the Web.
@brentru thanks.
